import { listSuggestions } from '@/server/queries';
import { formatMoneyWhole } from '@/domain/money';
import { SuggestionRow } from '@/components/app/suggestion-row';

export const dynamic = 'force-dynamic';

function isoDate(date: Date | null): string {
  return date ? date.toISOString().slice(0, 10) : '—';
}

/** AI Suggestions — pending replenishment recommendations with reasoning. */
export default async function AiSuggestionsPage() {
  const suggestions = await listSuggestions();

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Suggestions</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {suggestions.length} pending {suggestions.length === 1 ? 'suggestion' : 'suggestions'} — generated by the
          replenishment engine from live stock levels, sales velocity, and supplier lead times.
        </p>
      </div>

      {suggestions.length === 0 ? (
        <p className="rounded-2xl bg-[#f3f4f6] p-6 text-sm text-muted-foreground">
          No pending suggestions. Everything is comfortably stocked — new suggestions appear here when a SKU is
          projected to fall below its reorder point.
        </p>
      ) : (
        <div className="flex flex-col gap-3">
          {suggestions.map((s) => (
            <SuggestionRow
              key={s.orderId}
              suggestion={{
                orderId: s.orderId,
                productId: s.productId,
                productName: s.productName,
                sku: s.sku,
                supplierName: s.supplierName,
                quantity: s.quantity,
                totalCost: formatMoneyWhole(s.totalCostMinor),
                expectedDelivery: isoDate(s.expectedDelivery),
                aiReasoning: s.aiReasoning,
                suggestedAt: isoDate(s.orderDate),
              }}
            />
          ))}
        </div>
      )}
    </div>
  );
}
